import { GenreTypes, RegionTypes } from '@types'

export const PERFORMANCE_SEARCH = {
  comming: [
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-28T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-28T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-03-01T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-28T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-03-02T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-03-02T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-03-02T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-03-03T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-28T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-28T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
  ],
  ended: [
    {
      id: 1,
      title: '저희 공연 합니다!',
      imgUrl: 'https://picsum.photos/400/500?random=1',
      startDate: '2023-02-10T12:00:00',
      location: '부산' as RegionTypes,
      genres: ['스트릿', '왁킹'] as GenreTypes[],
      profile: {
        id: '1',
        imgUrl: `https://picsum.photos/200/200?random=1`,
        name: '댄스팀',
      },
    },
  ],
}
