import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="font-pretendard text-[44px]">폰트 테스트</div>
        <div className=" text-[44px]">폰트 테스트</div>
        <div className="font-pretendard text-[44px] font-extrabold">
          123456789
        </div>
        <div className="text-[44px] font-extrabold">123456789</div>
      </main>
    </>
  )
}
